apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keekten-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: "keekten-static-ip-prod"
    networking.gke.io/managed-certificates: "keekten-cert"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keekten-service
            port:
              number: 80
