apiVersion: v1
kind: Pod
metadata:
  name: bff
  namespace: default
spec:
  containers:
  - name: bff
    image: asia-northeast1-docker.pkg.dev/keekten-docker-prod/bff
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP