apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: default
spec:
  replicas: 2
  containers:
  - name: bff
    image: asia-northeast1-docker.pkg.dev/keekten-docker-prod/bff
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
