apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bff
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: asia-northeast1-docker.pkg.dev/keekten-docker-prod/bff
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080 