apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: default
spec:
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      volumes:
      - name: firebase-key
        secret:
          secretName: fb-key
      containers:
      - name: bff
        image: asia-northeast1-docker.pkg.dev/keekten-docker-prod/bff:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: firebase-key
          mountPath: /var/secrets/google
        env:
        - name: PORT
          value: "8080"
        - name: TREE_SERVICE_ADDR
          value: "tree-service:50051" #tree.yamlを参照
        - name: FIREBASE_AUTH_CREDENTIALS
          value: /var/secrets/google/fb-key.json
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bff-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bff
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: keekten-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: bff
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
