apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff
        image: asia-northeast1-docker.pkg.dev/keekten-docker-prod/bff
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: TREE_SERVICE_ADDR
          value: "tree-service:50051" #tree.yamlを参照
---
apiVersion: v1
kind: Service
metadata:
  name: keekten-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: bff
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP