apiVersion: apps/v1
kind: Deployment
metadata:
  name: mission
  namespace: default
spec:
  selector:
    matchLabels:
      app: mission
  template:
    metadata:
      labels:
        app: mission
    spec:
      containers:
      - name: mission
        image: asia-northeast1-docker.pkg.dev/keekten-docker-prod/mission:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mission-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mission
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: mission-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: mission
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP