apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: default
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gsa-key
      containers:
      - name: user
        image: asia-northeast1-docker.pkg.dev/keekten-docker-prod/user:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: PORT
          value: "50051"
        - name: PROJECT_ID
          value: "plesio-407208"
        - name: TOPIC_NAME
          value: "act_to_tree-subscription"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        envFrom:
        - secretRef:
            name: user-env
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: user
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
