apiVersion: apps/v1
kind: Deployment
metadata:
  name: tree
  namespace: default
spec:
  replicas: 2
  containers:
  - name: tree
    image: asia-northeast1-docker.pkg.dev/keekten-docker-prod/tree
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
