name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main
    paths:
      - "mobile/**"
      - ".github/workflows/firebase-hosting-merge.yml"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build for the web
        run: flutter build web --release

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KIIKUTEN }}"
          channelId: live
          projectId: kiikuten
