name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    paths:
      - "mobile/**"
      - ".github/workflows/firebase-hosting-pull-request.yml"

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build for the web
        run: flutter build web --release
        # run: flutter build web --web-renderer html --release

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KIIKUTEN }}"
          expires: 7d
          projectId: kiikuten
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
