name: Lint

on:
  pull_request:
    paths:
      - 'services/**/*.go'
      - 'services/.golangci.yml'

env:
  GO_VERSION: 1.21

jobs:
  golangci-lint:
    name: runner/golangci-lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint with review dog
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: '--config=.golangci.yml'
          level: error
          reporter: github-pr-review
          go_version: ${{ github.env.GO_VERSION }}
          fail_on_error: true
